### ISSUE TITLE
Unable to update servers to 1.11.1

### ISSUE THREAD

**Issue by Huvik** [prismagraphql/prisma-cloud-feedback#182] opened 2018-07-09 11:21 UTC
I am unable to update cluster from version `1.10.2` to `1.11.1`, because select is empty. Api returns empty upgrades: 
![](https://i.imgur.com/q08ovOh.png)

**Comment by marktani** [comment] 2018-07-09 13:02
Prisma servers managed in Prisma Cloud can only be upgrade to `1.10.2` currently.

**Comment by Huvik** [comment] 2018-07-09 13:09
Ah, okay I didn't know that, because I was thinking that all non-beta releases are possible for cloud :)

**Comment by marktani** [comment] 2018-08-07 15:52
Closing as duplicate of https://github.com/prismagraphql/prisma-cloud-feedback/issues/186

**Closed by marktani** 2018-08-07 15:52 UTC
Labels: feature
